[package]
name = "colour-palette"
version = "0.1.1"
authors = ["russ"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "*"

